# Generated by Django 4.2.13 on 2024-05-31 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='1 Fake Street', max_length=100)),
                ('city', models.CharField(default='Manhattan', max_length=30)),
                ('state', models.CharField(default='NY', max_length=2)),
                ('zip_code', models.CharField(default='10001', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=10)),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fitnessclub.location')),
            ],
        ),
    ]
