# Generated by Django 4.2.13 on 2024-06-03 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessclub', '0005_class_classschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='day',
            field=models.CharField(default='Monday', max_length=50),
        ),
        migrations.AddField(
            model_name='class',
            name='time',
            field=models.CharField(default='5PM - 6PM', max_length=50),
        ),
        migrations.DeleteModel(
            name='ClassSchedule',
        ),
    ]
